version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: spring-security-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_spring:/var/lib/postgresql

volumes:
  pgdata_spring: